/* Clefwork Terms — the vocabulary list for the Vocabulary tab. The first six categories are the
   bold-face terms of the course textbook (Larsen, "Harmony in Contemporary Music", rev. July 29, 2026),
   defined as the book defines them, with the page each comes from; the last four are other common
   terms. Some book categories also hold a few common terms (pg 0), so a quiz can keep to the book.
   Each entry: [term, definition, textbook page (0: not from the book), tags]. Two terms that share
   a tag could both fit one definition (half step and semitone), so they never share a question. A
   general term carries the tag of every specific term it also describes — interval has one for each
   kind of interval, and a first inversion is also an inversion — while the specific ones have only
   their own, so a major and a minor interval can still be choices together.
   The list only grows at the end of each category's entries, and each entry added later carries the
   generator version it arrived in, so a quiz code keeps its questions. */
(function (root) {
  'use strict';
  const MQ = (root.MQ = root.MQ || {});
  const CATS = [
    { id: 'notation', label: 'Pitch & notation', book: 1, terms: [
      ['pitch', 'A musical sound, measured in hertz (A = 440 Hz)', 7],
      ['note', 'The name given to a pitch, such as A for 440 Hz', 7],
      ['half step', 'The smallest common distance between two pitches — from one piano key to the very next', 12, 'half'],
      ['whole step', 'Two half steps joined together', 7],
      ['semitone', 'Another name for a half step', 7, 'half'],
      ['musical alphabet', 'The seven letter names of the notes, A B C D E F G', 12],
      ['accidental', 'A sharp, flat, natural, double sharp or double flat that alters a note', 7, 'acS acF acN acSS acFF'],
      ['sharp (♯)', 'Raises a note by a half step', 7, 'acS'],
      ['flat (♭)', 'Lowers a note by a half step', 7, 'acF'],
      ['natural sign (♮)', 'Cancels any accidental', 7, 'acN'],
      ['double sharp', 'Raises a note by a whole step', 7, 'acSS'],
      ['double flat', 'Lowers a note by a whole step', 7, 'acFF'],
      ['enharmonic', 'One pitch with two different note names, such as A♯ and B♭', 13],
      ['staff', 'The five horizontal lines that notes are written on (also called a stave)', 14],
      ['clef', 'The sign at the start of a staff that shows which note each line and space is', 14, 'clT clB clA'],
      ['treble clef', 'The clef for higher notes; it curls around the G line', 14, 'clT'],
      ['bass clef', 'The clef for lower notes and lower instruments; its dots surround the F line', 15, 'clB'],
      ['alto clef', 'A C clef between the treble and bass clefs, used mostly by the viola', 16, 'clA'],
      ['ledger lines', 'Short lines that extend the staff above or below it', 15],
      ['middle C', 'The C in the middle of the piano keyboard, also called C4', 14],
      ['octave designation', 'Naming which octave a note is in with a number, such as C4', 17],
      ['pitched percussion', 'Percussion instruments that play specific pitches, like timpani and marimba', 17],
      ['unpitched percussion', 'Percussion instruments with no specific pitch, like the snare drum and cymbals', 17],
      ['timbre', 'The quality of a sound — light, dark, bright, harsh or mellow', 7],
    ] },
    { id: 'rhythm', label: 'Rhythm & meter', book: 1, terms: [
      ['beat', 'The steady pulse you tap your foot to', 22, 'beatD'],
      ['bar (measure)', 'A group of beats, marked off by bar lines', 22],
      ['meter', 'How the beats are grouped and divided, shown by the time signature', 21, 'meter mD mT'],
      ['time signature', 'The two numbers that tell how many beats are in each bar and which note gets the beat', 23, 'meter'],
      ['tempo', 'How fast the beat goes', 21, 'bpm'],
      ['beats per minute (BPM)', 'The unit that tempo is measured in', 23, 'bpm'],
      ['subdivision', 'The equal smaller parts that a note or beat divides into', 21],
      ['downbeat', 'A note on the beat itself — counted 1, 2, 3, 4', 24, 'beatD'],
      ['upbeat', 'The second half of a beat, counted “and” (&)', 25],
      ['dot', 'Adds half of a note’s value to the note', 26],
      ['tie', 'A curved line joining two notes of the same pitch into one longer note', 26],
      ['beam', 'A thick line that joins short notes, grouping them by beats', 20],
      ['flag', 'The curved tail on a single eighth note or shorter note', 19],
      ['rest', 'A symbol for silence, counted just like a note of the same value', 21],
      ['beat grouping', 'Writing rhythms so the beats of the bar are easy to see, to show the feel', 27],
      ['duple meter', 'A meter whose beats divide into two equal parts', 28, 'mD'],
      ['triple meter', 'A meter whose beats divide into three equal parts, usually with 8 on the bottom', 29, 'mT'],
      ['syncopation', 'Accents or long notes placed off the beat', 0],
      ['triplet', 'Three notes played in the time of two', 0],
      ['pickup (anacrusis)', 'One or more notes that come before the first full bar', 0],
      ['common time', '4/4 time, written as a C', 0],
      ['cut time', '2/2 time, written as a C with a line through it', 0],
    ] },
    { id: 'scales', label: 'Scales & keys', book: 1, terms: [
      ['major scale', 'The scale nearly all Western music is based on: whole, whole, half, whole, whole, whole, half', 31, 'ionian'],
      ['key signature', 'The sharps or flats at the start of each staff, always written in the same order', 32],
      ['circle of fifths', 'A chart of the keys arranged a fifth (or a fourth) apart', 10],
      ['imaginary key', 'A key not found on the circle because it’s enharmonic to a simple key, such as A♯ major', 33],
      ['solfège', 'A system that gives each note of a scale a syllable: do, re, mi …', 34],
      ['natural minor', 'The minor scale with the same notes as its relative major; the basis of the other minor scales', 35, 'aeolian'],
      ['harmonic minor', 'Natural minor with a raised seventh', 37],
      ['melodic minor', 'Natural minor with a raised sixth and seventh going up, and natural minor coming down', 37],
      ['jazz melodic minor', 'Melodic minor with the raised sixth and seventh both going up and coming down', 39],
      ['relative minor', 'The minor key with the same key signature as a major key; it starts on the major scale’s sixth note', 36],
      ['parallel minor', 'The minor key that starts on the same note as a major key', 36],
      ['leading tone', 'The seventh note of a major scale, a half step below the tonic', 38],
      ['scale degree', 'A number given to each note of a scale, starting with 1', 43],
      ['mode', 'A scale made from another scale by starting on a different note of it', 43, 'ionian mo2 mo3 mo4 mo5 aeolian mo7'],
      ['Ionian', 'The mode on the 1st note of a major scale — the major scale itself', 43, 'ionian'],
      ['Dorian', 'The mode on the 2nd note of a major scale', 43, 'mo2'],
      ['Phrygian', 'The mode on the 3rd note of a major scale', 43, 'mo3'],
      ['Lydian', 'The mode on the 4th note of a major scale', 44, 'mo4'],
      ['Mixolydian', 'The mode on the 5th note of a major scale', 44, 'mo5'],
      ['Aeolian', 'The mode on the 6th note of a major scale — the natural minor', 44, 'aeolian'],
      ['Locrian', 'The mode on the 7th note of a major scale', 44, 'mo7'],
      ['pentatonic scale', 'A scale with only five notes', 44],
      ['chromatic scale', 'A scale made of every half step', 46],
      ['tonic', 'The first note of a scale — the home note of a key', 0],
    ] },
    { id: 'intervals', label: 'Intervals', book: 1, terms: [
      ['interval', 'The distance between two notes, measured in half steps or scale degrees', 49, 'ivP ivM ivm ivA ivd ivC ivO ivT ivU'],
      ['octave', 'The distance from a note to the next note with the same name', 67, 'ivO'],
      ['compound interval', 'An interval larger than an octave, such as a 9th', 48, 'ivC'],
      ['perfect interval', 'A unison, 4th, 5th or octave — early in the overtone series, so easy to tune', 51, 'ivP ivO ivU'],
      ['major interval', 'A 2nd, 3rd, 6th or 7th as it appears in the major scale above its first note', 49, 'ivM'],
      ['minor interval', 'A major interval made a half step smaller', 50, 'ivm'],
      ['augmented interval', 'A perfect or major interval made a half step larger', 50, 'ivA ivT'],
      ['diminished interval', 'A perfect or minor interval made a half step smaller', 50, 'ivd ivT'],
      ['overtone series', 'The pitches that sound naturally above a note, in simple ratios', 51],
      ['tritone', 'An interval of three whole steps, such as C up to F♯', 0, 'ivT'],
      ['unison', 'Two notes at exactly the same pitch', 0, 'ivU'],
    ] },
    { id: 'chords', label: 'Chords', book: 1, terms: [
      ['chord', 'Two or more intervals played at the same time', 56, 't3 t3M t3m t3a t3d t3s t3p c7 s7D s7F s7H'],
      ['root', 'The note a chord is built on and named for', 56, 'ct'],
      ['chord tone', 'One of the notes that make up a chord', 56, 'ct'],
      ['extension', 'A note added to a chord for color beyond its chord tones, such as a 9th, 11th or 13th', 56],
      ['alteration', 'A chord note raised or lowered by a half step, such as ♭9 or ♯11', 56],
      ['triad', 'A three-note chord built from 1-3-5', 56, 't3 t3M t3m t3a t3d t3s'],
      ['seventh chord', 'A four-note chord built from 1-3-5-7', 56, 'c7 s7D s7F s7H'],
      ['quality', 'The type of a chord: major, minor, augmented or diminished', 58],
      ['major triad', 'Root, major third and perfect fifth (1-3-5)', 57, 't3M'],
      ['minor triad', 'Root, minor third and perfect fifth (1-♭3-5)', 57, 't3m'],
      ['augmented triad', 'Root, major third and augmented fifth (1-3-♯5)', 57, 't3a'],
      ['diminished triad', 'Root, minor third and diminished fifth (1-♭3-♭5)', 57, 't3d'],
      ['suspended chord', 'Root, perfect fourth and perfect fifth (1-4-5) — the 4th takes the 3rd’s place', 57, 't3s sus'],
      ['power chord', 'Just a root and a perfect fifth (1-5)', 57, 't3p'],
      ['dominant seventh chord', 'A major triad with a minor (dominant) seventh added: 1-3-5-♭7', 58, 's7D'],
      ['fully diminished seventh chord', 'A diminished triad with a diminished seventh added', 59, 's7F'],
      ['half-diminished seventh chord', 'A diminished triad with a minor (dominant) seventh added', 59, 's7H'],
      ['suspension', 'Holding a pitch over from the previous sound to make a new chord, as in C7sus', 8, 'sus'],
      ['voicing', 'The order in which the notes of a chord are played by instruments or voices', 56, 'vc vC vO'],
      ['closed voicing', 'A voicing with all the chord’s notes within an octave', 56, 'vC'],
      ['open voicing', 'A voicing with the chord’s notes spread wider than an octave', 56, 'vO'],
      ['chord spelling', 'Writing down the notes of a chord on paper', 64],
      ['tertian harmony', 'Chords built by stacking thirds', 56],
      ['quartal harmony', 'Chords built by stacking fourths', 56],
      ['bass note', 'The lowest sounding note of a chord', 65],
      ['inversion', 'A chord with a note other than the root on the bottom', 56, 'inv i1 i2 i3'],
      ['root position', 'A chord with its root as the lowest note', 65],
      ['first inversion', 'A chord with its third as the lowest note', 65, 'i1'],
      ['second inversion', 'A chord with its fifth as the lowest note', 65, 'i2'],
      ['third inversion', 'A seventh chord with its seventh as the lowest note', 66, 'i3'],
      ['slash chord', 'A chord written with its bass note after a slash, such as F/A', 66, 'inv i1 i2 i3'],
      ['chord symbol', 'Letters and numbers that name a chord for a chord player, such as B♭ma7', 56],
      ['Roman numeral', 'A chord named by the scale degree of its root: capitals for major, lowercase for minor', 8, 'rn'],
      ['Nashville numbers', 'Plain numbers for chords by scale degree, common in country and rock', 56],
      ['diatonic chords', 'The chords built from the notes of a key', 72],
      ['figured bass', 'Numbers with a bass line that show the intervals, and so the inversions, of the chords above it', 72],
      ['chorale', 'Music built on chords in a set number of voices, usually four, each voice a note of the chord', 66],
    ] },
    { id: 'analysis', label: 'Analysis & form', book: 1, terms: [
      ['song', 'A musical composition with lyrics to sing', 8],
      ['composition', 'A musical piece with no lyrics to sing', 8],
      ['melody', 'The recognizable tune of a song or composition', 8],
      ['harmony', 'The chords that accompany a melody', 8, 'homo'],
      ['macro analysis', 'An overview of a piece’s melody, harmony and structure, like a lead sheet', 69],
      ['microanalysis', 'Explaining every single note in a musical score', 69],
      ['chord symbol analysis', 'Writing a chord symbol where each chord begins; it lasts until the next symbol', 70],
      ['Roman numeral analysis', 'Naming each chord by its place in the key, to show how a piece is built', 70, 'rn'],
      ['phrase', 'A musical sentence: one complete idea of melody and chords, often four measures long', 91, 'phB'],
      ['binary phrase', 'A question-and-answer pair of phrases: the first asks, the second answers', 91, 'phB'],
      ['blues form', 'Three four-bar phrases, AAB, from the twelve-bar blues', 91, 'blues'],
      ['section', 'A part of the form, labeled with a letter: A, B, C …', 94, 'secB secV'],
      ['song form (AABA)', 'Four 8-bar sections, AABA — 32 bars', 93],
      ['binary form (AB)', 'Two contrasting sections, A and B', 93],
      ['ternary form (ABA)', 'A section, a contrasting section, then the first section again', 93],
      ['12-bar blues', 'A twelve-bar form built from three four-bar phrases', 93, 'blues'],
      ['strophic', 'One section (A) repeated, as in a song with many verses', 93],
      ['through-composed', 'A form in which no section repeats: A B C D …', 93],
      ['rhythm changes', 'Song form based on the chords of “I Got Rhythm”', 93],
      ['bridge', 'The contrasting section in the middle of a form, often in a new key — the B of AABA', 94, 'bridge secB'],
      ['chorus', 'One time through the entire form', 94],
      ['introduction (intro)', 'A short piece of music that begins a composition', 94],
      ['coda', 'New music, not part of the form, that ends a composition', 94, 'end'],
      ['outro', 'The section that ends a piece, often based on part of the form', 94, 'end'],
      ['transition', 'A short section that connects one section to another', 94, 'between'],
      ['interlude', 'A short piece of music between two sections', 94, 'between'],
      ['tag', 'An ending made by repeating a small part of the form, often the last 2 to 4 bars', 94, 'end'],
      ['turnaround', 'A short chord progression that leads back to the start of the form or a section', 94],
      ['solo (instrumental break)', 'A part of the form given to an instrumental solo', 94],
      ['verse', 'Slang for the part of a song that isn’t repeated', 94, 'secV'],
      ['pre-chorus', 'Slang for a transition that leads into the chorus (also rise or climb)', 94, 'between'],
      ['middle eight', 'Slang for the bridge', 94, 'bridge secB'],
    ] },
    { id: 'expression', label: 'Articulation & expression', book: 0, terms: [
      ['staccato', 'Short and detached', 0],
      ['legato', 'Smooth and connected', 0, 'smooth'],
      ['slur', 'A curved line over different notes, played smoothly in one breath or bow', 0, 'smooth'],
      ['accent', 'Played with extra emphasis', 0, 'accent'],
      ['marcato', 'Marked — strongly accented', 0, 'accent'],
      ['tenuto', 'Held for its full value, slightly stressed', 0],
      ['fermata', 'Hold the note longer than its value', 0],
      ['dolce', 'Sweetly', 0],
      ['cantabile', 'In a singing style', 0],
      ['espressivo', 'Expressively', 0],
      ['maestoso', 'Majestically', 0],
      ['con brio', 'With spirit and vigor', 0],
      ['sempre', 'Always', 0],
      ['molto', 'Very, or much', 0],
      ['poco a poco', 'Little by little', 0],
      ['subito', 'Suddenly', 0],
      ['simile', 'Keep going in the same way', 0],
    ] },
    { id: 'navigation', label: 'Repeats & road maps', book: 0, terms: [
      ['repeat sign', 'Play the music between the signs again', 0],
      ['first and second endings', 'Different endings for the first and second times through', 0],
      ['D.C. (da capo)', 'Go back to the beginning', 0, 'dc'],
      ['D.C. al Fine', 'Go back to the beginning and play to the word Fine', 0, 'dc'],
      ['D.S. (dal segno)', 'Go back to the sign', 0, 'ds'],
      ['D.S. al Coda', 'Go back to the sign, then jump to the coda at “To Coda”', 0, 'ds'],
      ['Fine', 'The end', 0],
      ['segno', 'The sign that D.S. sends you back to', 0],
    ] },
    { id: 'texture', label: 'Texture, ensembles & techniques', book: 0, terms: [
      ['monophony', 'One melody alone, with no accompaniment', 0],
      ['homophony', 'A melody with a chordal accompaniment', 0, 'homo'],
      ['polyphony', 'Two or more independent melodies at once', 0],
      ['a cappella', 'Singing without instruments', 0],
      ['duet', 'Music for two performers', 0],
      ['trio', 'Music for three performers', 0],
      ['quartet', 'Music for four performers', 0],
      ['pizzicato', 'Plucking the strings of a bowed instrument', 0],
      ['arco', 'Playing with the bow', 0],
      ['vibrato', 'A slight, rapid wavering of the pitch', 0],
      ['tremolo', 'A fast repetition of one note, or between two notes', 0],
      ['trill', 'A fast alternation between a note and the note above it', 0],
      ['glissando', 'A slide from one pitch to another', 0],
      ['mute', 'A device that softens or changes an instrument’s tone', 0],
    ] },
    { id: 'melody', label: 'Melody & harmony', book: 0, terms: [
      ['motif', 'A short musical idea that is repeated and developed', 0, 'rep'],
      ['ostinato', 'A short pattern repeated over and over', 0, 'rep'],
      ['sequence', 'A pattern repeated starting on a higher or lower pitch', 0],
      ['arpeggio', 'The notes of a chord played one after another', 0],
      ['stepwise motion', 'A melody moving from each note to the next letter name', 0],
      ['leap', 'A melody moving by an interval larger than a step', 0],
      ['range', 'The span from the lowest note to the highest', 0],
      ['modulation', 'A change from one key to another within a piece', 0, 'key'],
      ['transposition', 'Moving music into a different key, keeping it otherwise the same', 0, 'key'],
      ['consonance', 'Notes that sound stable and at rest together', 0],
      ['dissonance', 'Notes that sound tense together and want to resolve', 0],
      ['cadence', 'A harmonic resting point at the end of a phrase', 0, 'cadA cadH cadP cadD'],
      ['authentic cadence', 'A cadence from V to I', 0, 'cadA'],
      ['half cadence', 'A phrase that ends on V', 0, 'cadH'],
      ['plagal cadence', 'A cadence from IV to I — the “Amen” cadence', 0, 'cadP'],
      ['deceptive cadence', 'A cadence from V to vi instead of I', 0, 'cadD'],
    ] },
  ];
  // One flat list: {id, term, means, pg, cat (index), tags, since}.
  const VOCAB = [];
  CATS.forEach((c, ci) => c.terms.forEach(([term, means, pg, tags, since]) => {
    VOCAB.push({ id: `${c.id}:${term}`, term, means, pg: pg || 0, cat: ci, tags: tags ? tags.split(' ') : [], since: since || 1 });
  }));
  Object.assign(MQ, { TERM_VOCAB: VOCAB, TERM_VOCAB_CATS: CATS.map((c) => ({ id: c.id, label: c.label, book: c.book, count: c.terms.length, fromBook: c.terms.filter((t) => t[2]).length })) });
})(typeof window !== 'undefined' ? window : globalThis);
